# Generated by Django 3.0 on 2019-12-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_correcao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='data',
            field=models.DateField(),
        ),
    ]
